//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomeFeild
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public string ControlType { get; set; }
        public string ControlName { get; set; }
    }
}
