//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class school
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Princepal { get; set; }
        public string UserName { get; set; }
        public string Pasword { get; set; }
        public int LastEditedBy { get; set; }
        public int UserID { get; set; }
        public System.DateTime LastEditedOn { get; set; }
        public short IsActive { get; set; }
        public short IsExpired { get; set; }
        public string Logo { get; set; }
    }
}
